server:
  port: 8072

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  application.name: microservice-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
      discovery.locator.enabled: true
      routes:
        - id: service-user-id
          uri: lb://USER
          predicates:
            Path=/api/v1/user/**
        - id: service-booking-id
          uri: lb://BOOKING
          predicates:
            - Path=/api/v1/booking/**
        - id: service-host-id
          uri: lb://HOST
          predicates:
            Path=/api/v1/host/**
          filters:
            - AuthFilter



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
